const {PGlite} = await import(process.env.PGLITE_MODULE);
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',c='00000000-0000-4000-8000-000000000003';
await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key,is_anonymous boolean default false,banned_until timestamptz,email text);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 grant usage on schema auth to authenticated,anon;
 insert into auth.users(id,email) values('${a}','private-a@example.test'),('${b}','private-b@example.test'),('${c}','private-c@example.test');`);
await db.exec(`create schema storage;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
 create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);
 alter table storage.objects enable row level security;
 grant usage on schema storage to authenticated;
 grant select,insert on storage.objects to authenticated;
 create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;`);
await db.exec(fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609170012_chat.sql','utf8'));
await db.exec('create table public.app_notices(id uuid primary key);');
let seq=0;const id=()=>`11111111-1111-4111-8111-${String(++seq).padStart(12,'0')}`;
async function user(u){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u]);await db.exec('set role authenticated');}
const call=async(action,data={})=>(await db.query('select public.chat_api_v1($1,$2) r',[action,data])).rows[0].r;
await user(a);const directory=await call('directory');assert.equal(directory.length,3);assert.equal(JSON.stringify(directory).includes('email'),false);
await call('profile',{nickname:'甲学友'});
const direct=(await call('direct',{user_id:b})).id;
const message=id();await call('send',{room_id:direct,id:message,body:'你好'});await call('send',{room_id:direct,id:message,body:'你好'});
assert.equal((await call('messages',{room_id:direct})).length,1);
await user(b);assert.equal((await call('direct',{user_id:a})).id,direct);assert.equal((await call('rooms'))[0].unread,1);
const messages=await call('messages',{room_id:direct});await call('read',{room_id:direct,at:messages[0].created_at});assert.equal((await call('rooms'))[0].unread,0);
await assert.rejects(()=>call('recall',{room_id:direct,id:message}));
await user(c);assert.equal((await db.query('select * from public.chat_messages')).rows.length,0);
await assert.rejects(()=>call('messages',{room_id:direct}));await assert.rejects(()=>call('send',{room_id:direct,id:id(),body:'intrusion'}));
await assert.rejects(()=>db.query('update public.chat_members set user_id=$1',[c]));
await user(a);await call('recall',{room_id:direct,id:message});assert.equal((await call('messages',{room_id:direct}))[0].body,'');
const filePath=`${direct}/${a}/test.png`;
await db.query('insert into storage.objects(bucket_id,name) values ($1,$2)',['chat-files',filePath]);
await call('send',{room_id:direct,id:id(),body:'test.png',attachment_path:filePath,attachment_name:'test.png',attachment_kind:'image'});
await user(b);assert.equal((await db.query('select * from storage.objects')).rows.length,1);
await user(c);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await assert.rejects(()=>db.query('insert into storage.objects(bucket_id,name) values ($1,$2)',['chat-files',`${direct}/${c}/bad.png`]));
await user(a);
await call('block',{user_id:b,blocked:true});await user(b);await assert.rejects(()=>call('send',{room_id:direct,id:id(),body:'blocked'}));
await user(a);await call('block',{user_id:b,blocked:false});
const group=id();await call('create_group',{id:group,title:'共修交流',members:[b,c]});
await call('create_group',{id:group,title:'共修交流',members:[b,c]});
await user(b);await call('send',{room_id:group,id:id(),body:'群消息'});
await assert.rejects(()=>call('remove',{room_id:group,user_id:c}));
await assert.rejects(()=>call('rename',{room_id:group,title:'forbidden'}));
await user(a);await call('rename',{room_id:group,title:'学修群'});await call('remove',{room_id:group,user_id:c});
await user(c);await assert.rejects(()=>call('messages',{room_id:group}));
assert.equal((await db.query('select * from public.chat_messages')).rows.length,0);
await user(a);await call('invite',{room_id:group,user_id:c});
await user(c);assert.equal((await call('messages',{room_id:group})).length,1);await call('leave',{room_id:group});
await assert.rejects(()=>call('messages',{room_id:group}));
await db.exec('reset role;set role anon');await assert.rejects(()=>call('directory'));await assert.rejects(()=>db.query('select * from public.chat_profiles'));
console.log('PASS chat SQL: private directory, direct uniqueness, UUID retry, unread/read, recall ownership, block, groups, owner-only management, removed-member RLS, anonymous denial.');
await db.exec('reset role; alter table storage.objects add column metadata jsonb');
const migration=fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609180031_group_learning.sql','utf8');
await db.exec(migration);await db.exec(migration);
const groupApi=async(action,data={})=>(await db.query('select public.group_learning_v1($1,$2) r',[action,{group_id:group,...data}])).rows[0].r;
await user(a);await groupApi('settings',{all_muted:true});
await user(b);await assert.rejects(()=>call('send',{id:id(),room_id:group,body:'muted'}),/GROUP_MUTED/);
await assert.rejects(()=>groupApi('content',{id:id(),kind:'announcement',title:'no'}));
await user(a);await groupApi('role',{user_id:b,role:'admin'});
await user(b);await call('send',{id:id(),room_id:group,body:'manager allowed'});
const announcement=id();await groupApi('content',{id:announcement,kind:'announcement',title:'共修安排',body:'明天'});
await groupApi('read',{id:announcement});assert.equal((await groupApi('overview')).items[0].read_count,1);
const fid=id(),objectKey=`${group}/${b}/${fid}`;
await assert.rejects(()=>db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['group-files',objectKey,{size:100}]));
await groupApi('file_reserve',{id:fid,file_size:100});
await assert.rejects(()=>db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['group-files',objectKey,{size:101}]));
await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['group-files',objectKey,{size:100}]);
await groupApi('file_add',{id:fid,file_name:'讲义.pdf',file_size:100,checksum:'a'.repeat(64)});
assert.equal((await groupApi('search',{query:'讲义'})).files.length,1);
await user(c);await assert.rejects(()=>groupApi('overview'));assert.equal((await db.query("select * from storage.objects where name=$1",[objectKey])).rows.length,0);
await user(a);await call('invite',{room_id:group,user_id:c});
await user(c);assert.equal((await groupApi('overview')).files.length,1);
await user(a);await groupApi('settings',{all_muted:false,history_files:false});
await user(c);assert.equal((await groupApi('overview')).files.length,0);
await user(a);await groupApi('settings',{all_muted:false,history_files:true});
const practice=id();await groupApi('practice_create',{id:practice,title:'念佛',target:1000000});
await user(c);await groupApi('join_practice',{id:practice});const event=id();await groupApi('count',{id:practice,event_id:event});await groupApi('count',{id:practice,event_id:event});
assert.equal((await groupApi('overview')).practices[0].total,1);const batch=[id(),id()];await groupApi('count_many',{id:practice,event_ids:[event,...batch]});await groupApi('count_many',{id:practice,event_ids:batch});assert.equal((await groupApi('overview')).practices[0].total,3);
await user(a);await groupApi('mute',{user_id:c,until:'infinity'});
await user(c);await assert.rejects(()=>call('send',{id:id(),room_id:group,body:'muted'}),/GROUP_MUTED/);
await user(b);await assert.rejects(()=>groupApi('role',{user_id:c,role:'admin'}));
await user(a);await groupApi('file_remove',{id:fid});assert.equal((await groupApi('overview')).files.length,0);
await user(a);await call('remove',{room_id:group,user_id:b});await call('invite',{room_id:group,user_id:b});await user(b);assert.equal((await groupApi('overview')).manager,false);
console.log('PASS groups: admin roles, database mute, member isolation, upload reservation, historic files permission, Chinese search, announcement reads, practice retries, metadata retirement');
await db.exec('reset role;alter table public.chat_messages add column attachment_size bigint;');
const apkMigration=fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609200042_apk_sharing.sql','utf8');
await db.exec(apkMigration);await db.exec(apkMigration);
await db.exec('create trigger test_apk_size before insert on public.chat_messages for each row execute function public.chat_attachment_size()');
await user(a);
const apkId=id(),apkPath=`${direct}/${a}/${apkId}.apk`;
await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['chat-files',apkPath,{size:200000000,mimetype:'application/vnd.android.package-archive'}]);
const posted=await call('send',{id:apkId,room_id:direct,body:'app.apk',attachment_path:apkPath,attachment_name:'app.apk',attachment_kind:'file'});
assert.equal(posted.attachment_size,200000000);assert.equal(posted.attachment_mime_type,'application/vnd.android.package-archive');
await user(b);assert.equal((await db.query('select name from storage.objects where name=$1',[apkPath])).rows.length,1);
await user(c);assert.equal((await db.query('select name from storage.objects where name=$1',[apkPath])).rows.length,0);
await user(a);
const gid=id(),gp=`${group}/${a}/${gid}.apk`;
await groupApi('file_reserve',{id:gid,file_size:200000000});
await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['group-files',gp,{size:200000000,mimetype:'application/vnd.android.package-archive'}]);
await groupApi('file_add',{id:gid,file_name:'app.apk',file_size:200000000,checksum:'a'.repeat(64)});
await groupApi('file_add',{id:gid,file_name:'app.apk',file_size:200000000,checksum:'a'.repeat(64)});
const overview=await groupApi('overview');assert.equal(overview.files.filter(f=>f.file_id===gid).length,1);assert.equal(overview.files.find(f=>f.file_id===gid).object_key,gp);
console.log('PASS APK 200MB chat metadata, recipient/outsider ACL, group .apk reservation, unchanged filename, duplicate retry, migration replay');
await db.close();
