-- Read-only: reports which migrations from 202609190038 onward appear to be
-- deployed, by checking one distinctive object each. Changes nothing.
with checks(migration, what, ok) as (values
 ('202609190038_forum_author_edits', 'function forum_author_write_v1',
   to_regprocedure('public.forum_author_write_v1(jsonb)') is not null),
 ('202609190040_friend_approval', 'function chat_friend_setting_v1',
   exists(select 1 from pg_proc where proname='chat_friend_setting_v1')),
 ('202609200041_forum_composer', 'column forum_attachments.sort_order',
   exists(select 1 from information_schema.columns where table_schema='public' and table_name='forum_attachments' and column_name='sort_order')),
 ('202609200042_apk_sharing', 'column attachment_mime_type',
   exists(select 1 from information_schema.columns where table_schema='public' and column_name='attachment_mime_type')),
 ('202609200043_long_notes', 'table note_committed_versions',
   to_regclass('public.note_committed_versions') is not null),
 ('202609200044_forum_display', 'function public_forum_avatar',
   exists(select 1 from pg_proc where proname='public_forum_avatar')),
 ('202609200045_jieyuan', 'table jieyuan_config',
   to_regclass('public.jieyuan_config') is not null),
 ('202609200046_jieyuan_admin', 'function huideng_admin_jieyuan',
   exists(select 1 from pg_proc where proname='huideng_admin_jieyuan')),
 ('202609200047_public_resources', 'table public_resources',
   to_regclass('public.public_resources') is not null),
 ('202609200048_public_resources_large_files', 'column verify_state',
   exists(select 1 from information_schema.columns where table_schema='public' and column_name='verify_state')),
 ('202609200049_resource_governance', 'table resource_user_limits',
   to_regclass('public.resource_user_limits') is not null),
 ('202609200050_public_resource_web_share', 'table public_resource_web_links',
   to_regclass('public.public_resource_web_links') is not null),
 ('202609200051_notes_favorite2', 'function preserve_note_favorite2',
   exists(select 1 from pg_proc where proname='preserve_note_favorite2')),
 ('202609210052_group_invites', 'function group_invite_v1',
   exists(select 1 from pg_proc where proname='group_invite_v1')),
 ('202609210053_group_storage_reservations', 'function validate_group_storage_reservation',
   exists(select 1 from pg_proc where proname='validate_group_storage_reservation')),
 ('202609210054_resource_discovery', 'function resource_display_type',
   exists(select 1 from pg_proc where proname='resource_display_type')),
 ('202609210055_private_note_links', 'table note_web_snapshots',
   to_regclass('public.note_web_snapshots') is not null),
 ('202609210056_personal_library', 'table personal_library_assets',
   to_regclass('public.personal_library_assets') is not null),
 ('202609210057_chat_recall', 'function chat_object_referenced',
   exists(select 1 from pg_proc where proname='chat_object_referenced')),
 ('202609210058_app_releases', 'table app_releases',
   to_regclass('public.app_releases') is not null),
 ('202609210060_resource_previews', 'function public_resource_preview',
   exists(select 1 from pg_proc where proname='public_resource_preview')),
 ('202609210061_group_management', 'function group_manage_v2',
   exists(select 1 from pg_proc where proname='group_manage_v2')),
 ('202609220062_friend_approval_precheck', 'function chat_directory_v2',
   exists(select 1 from pg_proc where proname='chat_directory_v2')),
 ('202609220065_unified_article_content_limit', 'forum body limit 5000000',
   exists(select 1 from pg_constraint where conname='forum_posts_body_check' and pg_get_constraintdef(oid) like '%5000000%')),
 ('202609230066_activity_links', 'table activity_links',
   to_regclass('public.activity_links') is not null),
 ('202609230067_public_resource_guest_read', 'function public_resource_guest_v1',
   exists(select 1 from pg_proc where proname='public_resource_guest_v1')),
 ('202609230068_public_profile_links', 'function community_public_profile_v1',
   exists(select 1 from pg_proc where proname='community_public_profile_v1')),
 ('202609250070_forum_edit_images', 'function forum_author_write_v2',
   exists(select 1 from pg_proc where proname='forum_author_write_v2'))
)
select migration, what, case when ok then '已部署' else '缺少' end as status
from checks order by migration;
