import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE);
const db=new PGlite();
await db.exec(`create schema auth;create table auth.users(id uuid primary key);create role anon;create role authenticated;
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
create function auth.jwt() returns jsonb language sql as $$ select '{}'::jsonb $$;
insert into auth.users values('00000000-0000-4000-8000-000000000001'),('00000000-0000-4000-8000-000000000002');`);
for(const file of ['202609170009_forum_read.sql','202609170010_forum_interactions.sql','202609170011_forum_personal_lists.sql']) await db.exec(await readFile(new URL('../migrations/'+file,import.meta.url),'utf8'));
const user='00000000-0000-4000-8000-000000000001',other='00000000-0000-4000-8000-000000000002';
const id='10000000-0000-4000-8000-000000000001',reply='20000000-0000-4000-8000-000000000001';
const call=async(action,data={})=>(await db.query('select forum_action_v1($1,$2::jsonb) as result',[action,JSON.stringify(data)])).rows[0].result;
const post={id,title:'佛法交流',body:'正文测试',category_id:'study'};
await db.exec('set role anon');await assert.rejects(call('create',post),/login_required/);
await db.exec(`reset role;set test.uid='${user}';set role authenticated`);
assert.equal((await call('create',post)).id,id);
assert.equal((await call('create',post)).duplicate,true);
await assert.rejects(call('create',{...post,id:'10000000-0000-4000-8000-000000000003'}),/rate_limited/);
await call('reply',{id:reply,post_id:id,body:'第一条回复'});
assert.equal((await call('reply',{id:reply,post_id:id,body:'第一条回复'})).duplicate,true);
await call('like',{post_id:id,enabled:true});await call('like',{post_id:id,enabled:true});
await call('bookmark',{post_id:id,enabled:true});
let detail=await call('detail',{post_id:id});assert.equal(detail.post.reply_count,1);assert.equal(detail.post.like_count,1);assert.equal(detail.replies.length,1);assert.equal(detail.bookmarked,true);assert.equal(detail.post.author_user_id,undefined);
assert.equal((await call('mine')).items.length,1);assert.equal((await call('bookmarks')).items.length,1);
await assert.rejects(db.exec("update forum_posts set is_pinned=true"));
await db.exec(`reset role;set test.uid='${other}';set role authenticated`);
await assert.rejects(call('create',post),/request_conflict/);
assert.equal((await call('detail',{post_id:id})).bookmarked,false);assert.equal((await call('bookmarks')).items.length,0);assert.equal((await call('mine')).items.length,0);
await call('like',{post_id:id,enabled:false});assert.equal((await call('detail',{post_id:id})).post.like_count,1);
await db.exec(`reset role;update forum_posts set comments_closed=true where id='${id}';set role authenticated`);
await assert.rejects(call('reply',{id:'20000000-0000-4000-8000-000000000002',post_id:id,body:'关闭后回复'}),/replies_closed/);
await db.exec(`reset role;insert into forum_restrictions(user_id,blocked) values('${other}',true);set role authenticated`);
await assert.rejects(call('like',{post_id:id,enabled:true}),/account_restricted/);
await db.exec(`reset role;update forum_posts set visibility='hidden' where id='${id}';set role anon;set test.uid=''`);
await assert.rejects(call('detail',{post_id:id}),/post_unavailable/);
await db.close();console.log('PASS: authenticated publish/reply; UUID retries; rate limit; counters; private bookmarks; ownership; forbidden direct writes; closed replies; blocked account; hidden post.');
