import {PGlite} from '../../../../work/admin-sql-tests/package/dist/index.js';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const ids=Array.from({length:6},(_,i)=>`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`);
const [a,b,c,guest,outsider,banned]=ids;
const migration=n=>fs.readFileSync(new URL('../migrations/'+n,import.meta.url),'utf8');
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;
create table auth.users(id uuid primary key,is_anonymous boolean default false,banned_until timestamptz);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated;
create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
create table storage.objects(bucket_id text,name text,metadata jsonb);alter table storage.objects enable row level security;
create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;
create table public.app_notices(id uuid primary key);`);
for(const id of ids)await db.query('insert into auth.users(id,is_anonymous,banned_until) values($1,$2,$3)',[id,id===guest,id===banned?'2099-01-01':null]);
// Apply the guest-auth guard substitution introduced by migration 021.
await db.exec(migration('202609170012_chat.sql').replaceAll('not coalesce(is_anonymous,false)','true').replaceAll('not coalesce(u.is_anonymous,false)','true'));
await db.exec(migration('202609180031_group_learning.sql'));
await db.exec(migration('202609180024_chat_numbers_capacity.sql').split('do $$')[0]+'commit;');
await db.exec(migration('202609210052_group_invites.sql'));
const user=async u=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u]);await db.exec('set role authenticated');};
const call=async(action,data={})=>(await db.query('select public.chat_api_v1($1,$2) r',[action,data])).rows[0].r;
const invite=async(room,users)=>(await db.query('select public.group_invite_v1($1,$2) r',[room,users])).rows[0].r;
const manage=async(action,data)=>(await db.query('select public.group_manage_v2($1,$2) r',[action,data])).rows[0].r;
await user(a);await call('directory');
const group=crypto.randomUUID();await call('create_group',{id:group,title:'Original',members:[b]});
await assert.rejects(()=>invite(group,[guest]),/CHAT_INVALID_USER/);
console.log('REPRODUCED old guest invitation: CHAT_INVALID_USER');
await db.exec('reset role');
await db.exec(migration('202609210061_group_management.sql'));
await db.exec(migration('202609210061_group_management.sql'));
await user(b);assert.equal((await invite(group,[c,guest])).added,2);
assert.equal((await invite(group,[guest,c])).added,0);
await user(guest);assert.equal((await call('rooms')).some(r=>r.id===group),true);
await assert.rejects(()=>manage('rename',{room_id:group,title:'No'}),/CHAT_MANAGER_REQUIRED/);
await user(outsider);await assert.rejects(()=>invite(group,[outsider]),/CHAT_NOT_MEMBER/);
await assert.rejects(()=>manage('rename',{room_id:group,title:'No'}),/CHAT_NOT_MEMBER/);
assert.equal((await db.query('select * from chat_members where room_id=$1',[group])).rows.length,0);
await db.exec('reset role');
await db.query("insert into chat_group_roles(group_id,user_id,role) values($1,$2,'admin')",[group,b]);
await db.query('insert into chat_group_settings(group_id,managers_invite_only) values($1,true)',[group]);
await user(c);await assert.rejects(()=>invite(group,[outsider]),/CHAT_MANAGER_REQUIRED/);
await user(b);assert.equal((await manage('info',{room_id:group})).can_rename,true);
await manage('rename',{room_id:group,title:'Renamed'});
await user(guest);assert.equal((await call('rooms')).find(r=>r.id===group).title,'Renamed');
assert.ok((await call('messages',{room_id:group})).some(m=>m.body.includes('Renamed')&&m.is_system));
await db.exec('reset role');await db.query('update chat_rooms set member_limit=4 where id=$1',[group]);
await user(a);await assert.rejects(()=>invite(group,[outsider]),/CHAT_GROUP_SIZE/);
await assert.rejects(()=>invite(group,[banned]),/CHAT_INVALID_USER/);
const direct=(await call('direct',{user_id:b})).id;
const message=crypto.randomUUID();await call('send',{room_id:direct,id:message,body:'Retain private history'});
const newId=crypto.randomUUID(),params={room_id:direct,id:newId,users:[c,guest]};
assert.equal((await manage('from_direct',params)).id,newId);
assert.equal((await manage('from_direct',params)).id,newId);
assert.equal((await call('messages',{room_id:direct}))[0].body,'Retain private history');
assert.equal((await call('members',{room_id:direct})).length,2);
assert.equal((await call('members',{room_id:newId})).length,4);
await user(guest);assert.ok((await call('rooms')).some(r=>r.id===newId));
await assert.rejects(()=>call('messages',{room_id:direct}),/CHAT_NOT_MEMBER|CHAT_FORBIDDEN/);
await db.exec('reset role');
const rls=(await db.query("select bool_and(relrowsecurity) ok from pg_class where oid in ('chat_rooms'::regclass,'chat_members'::regclass,'chat_messages'::regclass)")).rows[0].ok;
assert.equal(rls,true);
await db.close();
console.log('PASS: guest/stranger multi-invite, duplicate, ownership/admin, manager setting, capacity, ban, new group retry, private history isolation, RLS');
