const {PGlite}=await import(process.env.PGLITE_MODULE);
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002';
await db.exec(`create role anon; create role authenticated;create schema auth;create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create function auth.jwt() returns jsonb language sql stable as $$select '{}'::jsonb$$;
grant usage on schema auth to anon,authenticated;
insert into auth.users values('${a}'),('${b}');
create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text,metadata jsonb);
alter table storage.objects enable row level security;
grant usage on schema storage to anon,authenticated;grant select,insert on storage.objects to authenticated;grant select on storage.objects to anon;
create function storage.foldername(text) returns text[] language sql as $$select string_to_array($1,'/')$$;`);
for(const f of ['202609170009_forum_read.sql','202609170010_forum_interactions.sql','202609170011_forum_personal_lists.sql','202609170016_forum_layout.sql'])await db.exec(fs.readFileSync('outputs/huideng_counter/supabase/migrations/'+f,'utf8'));
const p='11111111-1111-4111-8111-111111111111', q='11111111-1111-4111-8111-111111111112', file='22222222-2222-4222-8222-222222222222';
await db.query(`insert into public.forum_posts(id,author_user_id,author_name,category_id,title,body,visibility) values($1,$2,'学友','questions','历史问答','正文','published')`,[q,a]);
const user=async(u)=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u??'']);await db.exec(u?'set role authenticated':'set role anon');};
const action=async(action,data={})=>(await db.query('select public.forum_action_v2($1,$2) r',[action,data])).rows[0].r;
const feed=async(search='',category='',sort='latest')=>(await db.query('select public.forum_feed_v2($1,$2,$3,0) r',[search,category,sort])).rows[0].r.items;
await db.query(`update public.forum_posts set created_at=now()-interval '1 hour'`);
await user(a);
const path=`${a}/${p}/${file}`;
await db.query(`insert into storage.objects(bucket_id,name,metadata) values('forum-files',$1,'{"size":128}')`,[path]);
await user(b);assert.equal((await db.query('select * from storage.objects')).rows.length,0);
await user(a);
const payload={id:p,category_id:'resources',nickname:'学友甲',title:'资料',body:'内容',attachments:[{id:file,path,name:'修行讲义.pdf',kind:'file'}]};
await action('create',payload);assert.equal((await action('create',payload)).duplicate,true);
await user(null);
assert.equal((await feed('讲义')).length,1);assert.equal((await feed('','study'))[0].id,q);
assert.equal((await db.query('select * from storage.objects')).rows.length,1);
assert.equal((await db.query('select public.forum_sections_v1() r')).rows[0].r.length,4);
assert.equal((await action('detail',{post_id:p})).post.attachments.length,1);
await assert.rejects(()=>action('my_replies'));
await user(b);await action('reply',{id:'33333333-3333-4333-8333-333333333333',post_id:p,nickname:'乙',body:'回复'});
assert.equal((await action('my_replies')).items[0].id,p);
await action('like',{post_id:p,enabled:true});assert.equal((await feed('','','hot'))[0].id,p);
await assert.rejects(()=>db.query('insert into public.forum_attachments(id,post_id,owner_id,path,name,kind,size) values($1,$2,$3,$4,$5,$6,1)',[file,q,b,'x','x','file']));
await db.exec('reset role');await db.query("update public.forum_posts set visibility='hidden' where id=$1",[p]);
await user(null);assert.equal((await feed('讲义')).length,0);assert.equal((await db.query('select * from storage.objects')).rows.length,0);assert.equal((await db.query('select * from public.forum_attachments')).rows.length,0);
await assert.rejects(()=>action('detail',{post_id:p}));
console.log('PASS forum016: legacy category preserved, four real board summaries, filename search, popular order, own replies, UUID publication retry, unpublished/hidden attachments protected, anonymous write denied.');
await db.exec('reset role; alter table auth.users add column is_anonymous boolean default false; alter table auth.users add column banned_until timestamptz; create table public.chat_profiles(user_id uuid primary key,nickname text,avatar_path text)');
const migration=fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609180030_content_sharing.sql','utf8');
await db.exec(migration);await db.exec(migration);
await db.query("update public.forum_posts set visibility='published' where id=$1",[p]);
const v3=async (action,data={})=>(await db.query('select public.forum_action_v3($1,$2) r',[action,data])).rows[0].r;
const shared=async slug=>(await db.query('select public.shared_page_v1($1) r',[slug])).rows[0].r;

await db.exec('reset role');
const upgrade=fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609200041_forum_composer.sql','utf8');
await db.exec(upgrade);await db.exec(upgrade);
await db.exec("update public.forum_posts set created_at=now()-interval '1 hour'");
await user(a);
const newId='99999999-0000-4000-8000-000000000001';
const attachments=[];
for(let i=12;i>=1;i--){
 const id='88888888-0000-4000-8000-'+String(i).padStart(12,'0');
 const path=`${a}/${newId}/${id}`;
 await db.query("insert into storage.objects(bucket_id,name,metadata) values('forum-files',$1,$2)",[path,{size:128}]);
 attachments.push({id,path,name:`page-${13-i}.png`,kind:'image'});
}
const multi={id:newId,title:'分页测试',body:'完整正文',category_id:'study',tags:['佛学','测试'],attachments};
await v3('create',multi);
assert.equal((await v3('create',multi)).duplicate,true);
await assert.rejects(()=>v3('create',{...multi,attachments:[...attachments].reverse()}),/request_conflict/);
await assert.rejects(()=>v3('create',{...multi,tags:['不同']}),/request_conflict/);
assert.deepEqual((await v3('detail',{post_id:newId})).post.attachments.map(f=>f.id),attachments.map(f=>f.id));
assert.deepEqual((await v3('detail',{post_id:newId})).post.tags,['佛学','测试']);
await user(b);await assert.rejects(()=>v3('create',multi),/request_conflict/);
await db.exec('reset role');
await db.exec(fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609190038_forum_author_edits.sql','utf8'));
await db.exec("update public.forum_replies set created_at=now()-interval '1 hour'");
await user(b);await v3('like',{post_id:newId,enabled:true});await v3('bookmark',{post_id:newId,enabled:true});
await v3('reply',{id:'77777777-0000-4000-8000-000000000001',post_id:newId,body:'保留评论'});
await user(a);const itemBefore=(await v3('detail',{post_id:newId})).post;
const edit={post_id:newId,request_id:'66666666-0000-4000-8000-000000000001',operation:'edit',content_revision:itemBefore.content_revision,base_content:{title:itemBefore.title,body:itemBefore.body,rich_body:itemBefore.rich_body},title:'编辑原文',body:'更新正文',rich_body:null};
await db.query('select public.forum_author_write_v1($1)',[edit]);
const itemAfter=(await v3('detail',{post_id:newId})).post;
assert.equal(itemAfter.id,itemBefore.id);assert.equal(itemAfter.like_count,1);assert.equal(itemAfter.reply_count,1);
assert.deepEqual(itemAfter.attachments,itemBefore.attachments);
await user(b);assert.equal((await v3('detail',{post_id:newId})).bookmarked,true);
await assert.rejects(()=>db.query('select public.forum_author_write_v1($1)',[{...edit,request_id:'66666666-0000-4000-8000-000000000002'}]),/post_unavailable/);
await user(a);await v3('visibility',{post_id:newId,access_level:'private'});
await user(null);await assert.rejects(()=>v3('detail',{post_id:newId}),/post_unavailable/);

await db.exec('reset role');
const display=fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609200044_forum_display.sql','utf8');
await db.exec(display);await db.exec(display);
await user(a);await v3('visibility',{post_id:newId,access_level:'public'});
const original=(await v3('detail',{post_id:newId})).post;
const blank={post_id:newId,request_id:'66666666-0000-4000-8000-000000000009',operation:'edit',content_revision:original.content_revision,base_content:{title:original.title,body:original.body,rich_body:original.rich_body},title:'',body:'',rich_body:null};
await db.query('select public.forum_author_write_v1($1)',[blank]);
const edited=(await v3('detail',{post_id:newId}));
assert.equal(edited.post.title,'');assert.equal(edited.post.body,'');assert.equal(edited.post.like_count,1);assert.equal(edited.post.reply_count,1);assert.equal(edited.replies[0].user_id,b);
await db.exec("reset role; update public.forum_posts set created_at=now()-interval '1 hour'");await user(a);
const fresh='99999999-0000-4000-8000-000000000090';
await v3('create',{id:fresh,title:'',body:'正文原文',category_id:'study'});
assert.equal((await v3('detail',{post_id:fresh})).post.title,'');
await assert.rejects(()=>v3('create',{id:'99999999-0000-4000-8000-000000000091',title:'',body:'',category_id:'study'}));
await db.exec("reset role; update public.forum_posts set created_at=now()-interval '1 hour'");await user(a);
await v3('create',{id:'99999999-0000-4000-8000-000000000092',title:'文字分享',body:'用户真实标题',category_id:'study'});
assert.equal((await v3('detail',{post_id:'99999999-0000-4000-8000-000000000092'})).post.title,'文字分享');

await db.exec("reset role; update public.forum_posts set created_at=now()-interval '1 hour'");await user(a);
const picId='99999999-0000-4000-8000-000000000093', picFile='88888888-0000-4000-8000-000000000093',picPath=`${a}/${picId}/${picFile}`;
await db.query("insert into storage.objects(bucket_id,name,metadata) values('forum-files',$1,'{\"size\":128}')",[picPath]);
await v3('create',{id:picId,title:'',body:'',category_id:'study',attachments:[{id:picFile,path:picPath,name:'image.jpg',kind:'image'}]});
assert.equal((await v3('detail',{post_id:picId})).post.title,'');
await db.exec('reset role');
await db.query('insert into public.chat_profiles(user_id,nickname,avatar_path) values($1,$2,$3),($4,$5,$6)',[a,'A',`${a}/avatar.jpg`,b,'B',`${b}/private.jpg`]);
await db.query("insert into storage.objects(bucket_id,name,metadata) values('chat-avatars',$1,'{}'),('chat-avatars',$2,'{}')",[`${a}/avatar.jpg`,`${b}/private.jpg`]);
await user(null);
assert.equal((await feed()).find(p=>p.id===picId).author_user_id,a);
assert.equal((await db.query('select public.public_forum_avatar($1) p',[a])).rows[0].p,`${a}/avatar.jpg`);
assert.equal((await db.query('select public.public_forum_avatar($1) p',[b])).rows[0].p,null);
assert.equal((await db.query("select * from storage.objects where bucket_id='chat-avatars'")).rows.length,1);

await db.exec('reset role');
{
const jieyuanMigration=fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609200045_jieyuan.sql','utf8').replace(/^\uFEFF/,'');
await db.exec(jieyuanMigration);await db.exec(jieyuanMigration);
await db.exec("update public.forum_posts set created_at=now()-interval '2 days'");
await user(a);
const j={type:'free',status:'available',quantity:1,condition:'used',delivery:'both',postage:'discuss',country:'新西兰',region:'奥克兰',currency:'NZD'};
const id='44444444-4444-4444-8444-444444444445';
await v3('create',{id,title:'结缘经书',body:'品相良好',category_id:'jieyuan',jieyuan:j});
assert.equal((await v3('detail',{post_id:id})).post.jieyuan.region,'奥克兰');
assert.equal((await feed('结缘经书'))[0].jieyuan.type,'free');
assert.equal((await v3('mine')).items.find(x=>x.id===id).jieyuan.type,'free');
await v3('like',{post_id:id,enabled:true});
const itemBefore=(await v3('detail',{post_id:id})).post;
await db.query('select public.forum_author_write_v1($1)',[{post_id:id,request_id:'55555555-5555-4555-8555-555555555555',operation:'edit',content_revision:itemBefore.content_revision,base_content:{title:itemBefore.title,body:itemBefore.body,rich_body:itemBefore.rich_body},title:itemBefore.title,body:itemBefore.body,rich_body:itemBefore.rich_body,jieyuan:{...j,type:'paid',price:'20',quantity:2,status:'reserved'}}]);
const itemAfter=(await v3('detail',{post_id:id})).post;
assert.equal(itemAfter.id,itemBefore.id);assert.equal(itemAfter.like_count,1);assert.equal(itemAfter.jieyuan.price,'20');assert.equal(itemAfter.jieyuan.status,'reserved');
await db.exec('reset role');await db.exec("update public.jieyuan_levels set permissions=jsonb_set(permissions,'{daily_posts}','0') where level=1; update public.forum_posts set created_at=now()-interval '1 minute' where category_id='jieyuan'");
await user(a);await assert.rejects(()=>v3('create',{id:'44444444-4444-4444-8444-444444444447',title:'超额',body:'正文',category_id:'jieyuan',jieyuan:j}),/jieyuan_daily_limit/);
await db.exec('reset role');await db.exec("update public.jieyuan_levels set permissions=jsonb_set(permissions,'{daily_posts}','3') where level=1");
await user(a);
await db.exec('reset role');
await assert.rejects(()=>db.query("insert into public.forum_attachments(id,post_id,owner_id,path,name,kind,size) values(gen_random_uuid(),$1,$2,$3,'test.jpg','image',100)",[id,a,`${a}/${id}/quota.jpg`]),/jieyuan_image_limit/);
await user(b);assert.equal((await db.query('select public.jieyuan_inquire($1) r',[id])).rows[0].r.author_user_id,a);
await db.exec('reset role');await db.query("update public.forum_posts set jieyuan=jsonb_set(jieyuan,'{status}','\"completed\"') where id=$1",[id]);
await user(b);await assert.rejects(()=>db.query('select public.jieyuan_inquire($1)',[id]));
await db.query('select public.jieyuan_report($1,$2)',[id,'疑似侵权']);
await db.exec('reset role');await db.exec("update public.jieyuan_config set value=jsonb_set(value,'{enabled}','false')");
await user(b);assert.equal((await feed('结缘经书')).length,0);await assert.rejects(()=>v3('detail',{post_id:id}));
await db.exec('reset role');await db.exec("update public.jieyuan_config set value=jsonb_set(value,'{enabled}','true')");
await user(a);await assert.rejects(()=>v3('create',{id:'44444444-4444-4444-8444-444444444446',title:'价格测试',body:'正文',category_id:'jieyuan',jieyuan:{...j,type:'paid',price:-2}}));

await db.exec('reset role');
await db.exec(`create role service_role;create schema admin_private;
create table admin_private.members(user_id uuid,role text,enabled boolean);
create table admin_private.requests(actor uuid,request_id uuid,action text,payload jsonb,result jsonb,primary key(actor,request_id));
create table admin_private.audit_logs(actor uuid,action text,target text,after_data jsonb);
insert into admin_private.members values('${a}','super_admin',true);`);
await db.exec(fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609200046_jieyuan_admin.sql','utf8').replace(/^\uFEFF/,''));
const admin=async(actor,action,payload={})=>(await db.query('select public.huideng_admin_jieyuan($1,$2,$3,gen_random_uuid()) r',[actor,action,payload])).rows[0].r;
const config=await admin(a,'jieyuan.get');assert.equal(config.levels.length,5);
await admin(a,'jieyuan.save',config);
await admin(a,'jieyuan.level',{user_id:b,level:3});
assert.equal((await db.query('select level from public.app_user_levels where user_id=$1',[b])).rows[0].level,3);
await assert.rejects(()=>admin(b,'jieyuan.get'));
await admin(a,'jieyuan.moderate',{post_id:id,operation:'warn',message:'请核实分享权限'});
assert.equal((await db.query('select count(*)::int n from public.jieyuan_warnings')).rows[0].n,1);
await admin(a,'jieyuan.moderate',{post_id:id,operation:'hide'});
assert.equal((await db.query('select visibility from public.forum_posts where id=$1',[id])).rows[0].visibility,'hidden');
await user(b);await assert.rejects(()=>admin(a,'jieyuan.get'));
await db.close();console.log('PASS 045/046: item create/read/state gates, flags, validation, admin config/level/moderation, unauthorized denied');

}
