const {PGlite}=await import(process.env.PGLITE_MODULE);
import fs from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',admin='00000000-0000-4000-8000-000000000003';
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;create schema admin_private;
create table auth.users(id uuid primary key,is_anonymous boolean default false,banned_until timestamptz);
create table public.chat_profiles(user_id uuid,nickname text);create table public.forum_restrictions(user_id uuid,blocked boolean);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
create table admin_private.members(user_id uuid,role text,enabled boolean);
create table admin_private.audit_logs(actor uuid,action text,target text,before_data jsonb,after_data jsonb);
insert into auth.users(id) values('${a}'),('${b}'),('${admin}');insert into admin_private.members values('${admin}','super_admin',true);insert into chat_profiles values('${a}','甲'),('${b}','乙');`);
const sql=fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609200047_public_resources.sql','utf8').replace(/^\uFEFF/,'');await db.exec(sql);await db.exec(sql);
const rpc=async(actor,action,data={})=>(await db.query('select public.public_resources_service_v1($1,$2,$3) r',[actor,action,data])).rows[0].r;
const upload='11111111-1111-4111-8111-111111111111',lease='22222222-2222-4222-8222-222222222222';
const payload={upload_id:upload,file_name:'经书.pdf',file_size:2,checksum:'a'.repeat(64),category:'经论',description:'公开资料'};
let result=await rpc(a,'begin',payload);const id=result.file.id;
assert.equal((await rpc(a,'begin',payload)).file.id,id);await assert.rejects(()=>rpc(a,'begin',{...payload,file_size:3}),/UPLOAD_CONFLICT/);
assert.equal((await rpc(b,'list',{scope:'public'})).files.length,0);
await assert.rejects(()=>rpc(b,'complete',{upload_id:upload}),/FILE_UNAVAILABLE/);
await assert.rejects(()=>rpc(a,'complete',{upload_id:upload}),/UPLOAD_NOT_COMPLETE/);
await rpc(a,'upload.start',{upload_id:upload,lease_id:lease});
await assert.rejects(()=>rpc(a,'upload.start',{upload_id:upload,lease_id:lease}),/UPLOAD_BUSY/);
await rpc(a,'upload.verified',{upload_id:upload,lease_id:lease,size:2,checksum:payload.checksum});
await rpc(a,'complete',{upload_id:upload});assert.equal((await rpc(b,'list',{scope:'public'})).files.length,1);
assert.equal((await rpc(b,'download',{id})).file.id,id);
await assert.rejects(()=>rpc(a,'delete',{id}));await assert.rejects(()=>rpc(a,'admin.delete',{id}),/FORBIDDEN/);
let cfg=(await rpc(admin,'admin.list')).config;
await rpc(admin,'admin.settings',{...cfg,upload_enabled:false});
await assert.rejects(()=>rpc(a,'begin',payload),/UPLOAD_DISABLED/);assert.equal((await rpc(b,'download',{id})).file.id,id);
cfg=(await rpc(admin,'admin.list')).config;await rpc(admin,'admin.settings',{...cfg,upload_enabled:true,download_enabled:false});await assert.rejects(()=>rpc(b,'download',{id}),/DOWNLOAD_DISABLED/);
await rpc(admin,'admin.delete',{id});assert.equal((await rpc(b,'list',{scope:'public'})).files.length,0);assert.equal((await rpc(admin,'admin.cleanup')).files[0].id,id);
assert.equal((await rpc(admin,'admin.list')).config.used_bytes,2);await rpc(admin,'admin.purged',{id});assert.equal((await rpc(admin,'admin.list')).config.used_bytes,0);
await assert.rejects(()=>rpc(a,'upload.start',{upload_id:upload,lease_id:lease}),/FILE_UNAVAILABLE/);
await db.exec('set role authenticated');await assert.rejects(()=>rpc(a,'list',{}),/permission denied/);await assert.rejects(()=>db.query('select * from public.public_resources'),/permission denied/);await db.exec('reset role');
cfg=(await rpc(admin,'admin.list')).config;await rpc(admin,'admin.settings',{...cfg,total_bytes:1048576});
await rpc(a,'begin',{...payload,upload_id:'33333333-3333-4333-8333-333333333333',file_size:700000});
await assert.rejects(()=>rpc(b,'begin',{...payload,upload_id:'44444444-4444-4444-8444-444444444444',file_size:700000}),/RESOURCE_QUOTA_EXCEEDED/);
const active=(await rpc(a,'begin',{...payload,upload_id:'33333333-3333-4333-8333-333333333333',file_size:700000})).file;
await rpc(a,'upload.start',{upload_id:active.upload_id,lease_id:lease});
await rpc(admin,'admin.delete',{id:active.id});
assert.equal((await rpc(admin,'admin.cleanup')).files.length,0);
await rpc(admin,'admin.purged',{id:active.id});
assert.equal((await rpc(admin,'admin.list')).files[0].status,'deleting');
await db.exec(`insert into public.public_resources(user_id,upload_id,file_name,file_size,checksum,object_key,status,verified,created_at)
select '${a}',gen_random_uuid(),'文件'||(i%5)::text,1,repeat('a',64),'test/'||i,'published',true,now()-i*interval '1 second' from generate_series(1,107) i;`);
for(const sort of ['time','name','size']){
 let cursor=null;const ids=[];
 do {const page=await rpc(b,'list',{sort,cursor});ids.push(...page.files.map(x=>x.id));cursor=page.next_cursor;}while(cursor);
 assert.equal(ids.length,107);assert.equal(new Set(ids).size,107);
}
const upgrade=fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609200048_public_resources_large_files.sql','utf8');
await db.exec(upgrade);await db.exec(upgrade);
cfg=(await rpc(admin,'admin.list')).config;
assert.equal(cfg.max_file_bytes,536870912);assert.equal(cfg.total_bytes,1048576);assert.equal(cfg.download_enabled,false);
await rpc(admin,'admin.settings',{...cfg,total_bytes:1073741824});
const big=(await rpc(b,'begin',{...payload,upload_id:'55555555-5555-4555-8555-555555555555',file_name:'文殊.apk',file_size:314572800})).file;
assert.equal(big.mime_type,'application/vnd.android.package-archive');
await rpc(b,'upload.authorize',{upload_id:big.upload_id});
for(let offset=0;offset<big.file_size;offset+=8388608){
 await rpc(b,'upload.start',{upload_id:big.upload_id,lease_id:lease});
 const end=Math.min(offset+8388608,big.file_size);
 await assert.rejects(()=>rpc(b,'upload.verify_step',{upload_id:big.upload_id,lease_id:lease,expected_offset:offset+1,offset:end,state:Array(8).fill(1)}),/VERIFY_FAILED/);
 await rpc(b,'upload.verify_step',{upload_id:big.upload_id,lease_id:lease,expected_offset:offset,offset:end,state:Array(8).fill(1),checksum:big.checksum});
}
assert.equal((await rpc(b,'complete',{upload_id:big.upload_id})).file.status,'published');
await rpc(admin,'admin.delete',{id:big.id});
assert(!(await rpc(admin,'admin.cleanup')).files.some(x=>x.id===big.id));
await db.query("update public.public_resources set upload_token_until=now()-interval '1 second' where id=$1",[big.id]);
assert((await rpc(admin,'admin.cleanup')).files.some(x=>x.id===big.id));
await assert.rejects(()=>rpc(b,'begin',{...payload,upload_id:'66666666-6666-4666-8666-666666666666',file_size:536870913}),/FILE_TOO_LARGE/);
await db.close();console.log('PASS 047+048: isolation, verified publication, toggles, leases, quotas, pagination, 300 MiB APK, no early deletion while TUS capability remains valid');
