import fs from 'node:fs';import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE);const db=new PGlite();
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',admin='00000000-0000-4000-8000-000000000003';
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;create schema admin_private;
create table auth.users(id uuid primary key,is_anonymous boolean default false,banned_until timestamptz,email text,raw_user_meta_data jsonb default '{}',created_at timestamptz default now(),last_sign_in_at timestamptz);
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
create table public.chat_profiles(user_id uuid,nickname text);create table public.chat_presence(user_id uuid,seen_at timestamptz);
create table public.forum_restrictions(user_id uuid primary key,blocked boolean,muted boolean,updated_at timestamptz);
create table public.forum_posts(id uuid primary key,author_user_id uuid,title text,category_id text,access_level text,visibility text,deleted_at timestamptz,created_at timestamptz default now(),is_locked boolean,updated_at timestamptz);
create table public.forum_attachments(owner_id uuid,path text,name text,post_id uuid);create table public.community_files(owner_user_id uuid,bucket text,object_key text,file_name text);
create table public.app_user_levels(user_id uuid primary key,level integer);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,metadata jsonb,created_at timestamptz default now());
create table public.user_files(id uuid primary key,user_id uuid,bucket_name text,object_key text,file_name text,mime_type text,file_size bigint,upload_state text,created_at timestamptz default now());
create table admin_private.members(user_id uuid,role text,enabled boolean);
create table admin_private.audit_logs(actor uuid,action text,target text,before_data jsonb,after_data jsonb);
create table admin_private.requests(actor uuid,request_id uuid,action text,payload jsonb,result jsonb,primary key(actor,request_id));
insert into auth.users(id) values('${a}'),('${b}'),('${admin}');insert into admin_private.members values('${admin}','super_admin',true);insert into chat_profiles values('${a}','甲'),('${b}','乙');`);
const root='outputs/huideng_counter/supabase/migrations/';
for(const file of ['202609200047_public_resources.sql','202609200048_public_resources_large_files.sql','202609200049_resource_governance.sql'])await db.exec(fs.readFileSync(root+file,'utf8'));
await db.exec(fs.readFileSync(root+'202609200049_resource_governance.sql','utf8'));
const call=async(actor,action,payload={},request=crypto.randomUUID())=>(await db.query('select public.huideng_admin_usage($1,$2,$3,$4) r',[actor,action,payload,request])).rows[0].r;
const put=async(name,size,mime='application/octet-stream')=>db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['chat-files',`room/${a}/${name}`,{size,mimetype:mime}]);
await assert.rejects(()=>call(a,'usage.list'),/FORBIDDEN/);
let details=await call(admin,'usage.detail',{user_id:a});let lim=details.limits;
await call(admin,'usage.save',{...lim,user_id:a,level:2,quota_bytes:100,daily_bytes:200,monthly_bytes:300,daily_files:4,monthly_files:8});
await put('first.apk',60,'application/vnd.android.package-archive');
await assert.rejects(()=>put('second.pdf',50),/RESOURCE_USER_QUOTA/);
let list=(await call(admin,'usage.list',{sort:'apk'})).items;assert.equal(list[0].user_id,a);assert.equal(list[0].apk_bytes,60);assert.equal(list[0].day_download_bytes,null);
await assert.rejects(()=>call(admin,'usage.list',{sort:'download'}),/DOWNLOAD_USAGE_UNAVAILABLE/);
details=await call(admin,'usage.detail',{user_id:a});lim=details.limits;
await call(admin,'usage.save',{...lim,user_id:a,level:2,quota_bytes:50});
assert.equal((await call(admin,'usage.detail',{user_id:a})).files.length,1); // Lowered quota retains files.
await assert.rejects(()=>put('third.txt',1),/RESOURCE_USER_QUOTA/);
lim=(await call(admin,'usage.detail',{user_id:a})).limits;
await call(admin,'usage.save',{...lim,user_id:a,level:2,quota_bytes:1000,blocked_types:['apk'],types_until:new Date(Date.now()+3600000).toISOString()});
await assert.rejects(()=>put('fourth.apk',10),/RESOURCE_TYPE_BLOCKED/);
await put('allowed.png',10,'image/png');
lim=(await call(admin,'usage.detail',{user_id:a})).limits;
await call(admin,'usage.save',{...lim,user_id:a,level:2,daily_bytes:75});
await assert.rejects(()=>put('daily.txt',10),/RESOURCE_DAILY_LIMIT/);
await db.query('delete from storage.objects where name=$1',[`room/${a}/allowed.png`]);
details=await call(admin,'usage.detail',{user_id:a});assert.equal(details.user.used_bytes,60);assert.equal(details.user.day_upload_bytes,70);assert.equal(details.user.day_upload_files,2);
lim=(await call(admin,'usage.detail',{user_id:a})).limits;
await call(admin,'usage.save',{...lim,user_id:a,level:2,daily_bytes:1000,monthly_bytes:70});
await assert.rejects(()=>put('month.txt',1),/RESOURCE_MONTHLY_LIMIT/);
lim=(await call(admin,'usage.detail',{user_id:a})).limits;
await call(admin,'usage.save',{...lim,user_id:a,level:2,monthly_bytes:1000,daily_files:2});
await assert.rejects(()=>put('count.txt',1),/RESOURCE_DAILY_LIMIT/);
lim=(await call(admin,'usage.detail',{user_id:a})).limits;
await call(admin,'usage.save',{...lim,user_id:a,level:2,daily_files:100,monthly_files:2});
await assert.rejects(()=>put('month-count.txt',1),/RESOURCE_MONTHLY_LIMIT/);
const req=crypto.randomUUID();await call(admin,'usage.warn',{user_id:a,message:'请减少大文件上传'},req);await call(admin,'usage.warn',{user_id:a,message:'请减少大文件上传'},req);assert.equal((await call(admin,'usage.detail',{user_id:a})).warnings.length,1);
assert(!(JSON.stringify(details).includes('private_body')));
await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${b}',false);`);
await assert.rejects(()=>call(a,'usage.detail',{user_id:a}),/permission denied/);
assert.deepEqual((await db.query('select public.resource_my_warnings() r')).rows[0].r,[]);
await db.exec('reset role');
await call(admin,'usage.ban',{user_id:a});await assert.rejects(()=>put('banned.png',1,'image/png'),/RESOURCE_ACCOUNT_BANNED/);

const rpc=async(action,data={})=>(await db.query('select public.public_resources_service_v1($1,$2,$3) r',[b,action,data])).rows[0].r;
const upload=crypto.randomUUID();let item=(await rpc('begin',{upload_id:upload,file_name:'test.apk',file_size:20,checksum:'a'.repeat(64)})).file;
assert.equal((await call(admin,'usage.detail',{user_id:b})).user.pending_bytes,20);
await assert.rejects(()=>db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['public-resources',item.object_key,{size:21}]),/RESOURCE_UPLOAD_PAUSED/);
await db.query('insert into storage.objects(bucket_id,name,metadata) values($1,$2,$3)',['public-resources',item.object_key,{size:20}]);
assert.equal((await call(admin,'usage.detail',{user_id:b})).user.used_bytes,20);
assert.equal((await call(admin,'usage.detail',{user_id:b})).user.pending_bytes,0);
const lease=crypto.randomUUID();await rpc('upload.start',{upload_id:upload,lease_id:lease});await rpc('upload.verified',{upload_id:upload,lease_id:lease,size:20,checksum:'a'.repeat(64)});await rpc('complete',{upload_id:upload});
await call(admin,'usage.hide',{user_id:b,module:'public-resources',id:item.id});
assert.equal((await rpc('list')).files.length,0);await assert.rejects(()=>rpc('download',{id:item.id}),/FILE_UNAVAILABLE/);await assert.rejects(()=>rpc('complete',{upload_id:upload}),/FILE_UNAVAILABLE/);
let bl=(await call(admin,'usage.detail',{user_id:b})).limits;await call(admin,'usage.save',{...bl,user_id:b,level:1,paused:true});await assert.rejects(()=>rpc('begin',{upload_id:crypto.randomUUID(),file_name:'new.txt',file_size:1,checksum:'b'.repeat(64)}),/RESOURCE_UPLOAD_PAUSED/);
bl=(await call(admin,'usage.detail',{user_id:b})).limits;await call(admin,'usage.save',{...bl,user_id:b,level:1,paused_until:'2000-01-01T00:00:00Z'});
await rpc('begin',{upload_id:crypto.randomUUID(),file_name:'after-expiry.txt',file_size:1,checksum:'c'.repeat(64)});
await db.query('insert into forum_posts(id,author_user_id,title,category_id,access_level,visibility) values($1,$2,$3,$4,$5,$6)',[crypto.randomUUID(),b,'private-secret-title','study','private','published']);
assert(!(JSON.stringify(await call(admin,'usage.detail',{user_id:b})).includes('private-secret-title')));
await db.exec(`create table public.community_config(id boolean primary key,public_base_url text);insert into public.community_config values(true,'https://wenshu-web-service.onrender.com');`);
const migration50=fs.readFileSync('outputs/huideng_counter/supabase/migrations/202609200050_public_resource_web_share.sql','utf8');await db.exec(migration50);await db.exec(migration50);
const share=async()=> (await db.query('select public.public_resource_share_create($1,$2) r',[b,item.id])).rows[0].r;
await assert.rejects(share,/FILE_UNAVAILABLE/);
await db.query('update public.public_resources set moderated=false where id=$1',[item.id]);
const shared=await share();assert.equal((await share()).url,shared.url);
const token=shared.url.split('/').pop();assert(/^[a-f0-9]{64}$/.test(token));
const resolve=async(dl=false)=>(await db.query('select public.public_resource_web_resolve($1,$2) r',[token,dl])).rows[0].r;
assert(!('object_key' in await resolve()));assert((await resolve(true)).object_key);
await db.exec('update public.public_resource_settings set web_daily_signed_bytes=20');await assert.rejects(()=>resolve(true),/DOWNLOAD_LIMIT/);
await db.exec('update public.public_resource_settings set download_enabled=false');await assert.rejects(resolve,/DOWNLOAD_DISABLED/);
await db.exec('update public.public_resource_settings set download_enabled=true');
await call(admin,'usage.hide',{user_id:b,module:'public-resources',id:item.id});await assert.rejects(resolve,/FILE_UNAVAILABLE/);
await db.exec('set role anon');await assert.rejects(resolve,/permission denied/);await db.exec('reset role');
const protectedTables=await db.query("select relname,relrowsecurity from pg_class c join pg_namespace n on n.oid=c.relnamespace where (n.nspname='admin_private' and c.relname in ('resource_files','resource_upload_events','resource_web_daily')) or (n.nspname='public' and c.relname in ('resource_user_limits','resource_user_warnings','public_resource_web_links'))");
assert.equal(protectedTables.rows.length,6);assert(protectedTables.rows.every(x=>x.relrowsecurity));
console.log('PASS 050: stable random links, metadata isolation, signed-byte cap, disabled downloads, moderation, RPC access');
console.log('PASS 049: quotas, type/time limits, aggregation, immutable history, idempotent warnings, private access denied, ban enforcement');await db.close();
