import {PGlite} from '../../../../work/admin-sql-tests/package/dist/index.js';
import fs from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();const user='00000000-0000-4000-8000-000000000001',id='00000000-0000-4000-8000-000000000002';
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create schema storage;create schema admin_private;
create table auth.users(id uuid primary key,is_anonymous boolean,banned_until timestamptz);
create table public.chat_profiles(user_id uuid,nickname text);create table public.forum_restrictions(user_id uuid,blocked boolean);
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);
create table admin_private.members(user_id uuid,role text,enabled boolean);create table admin_private.audit_logs(actor uuid,action text,target text,before_data jsonb,after_data jsonb);
insert into auth.users values('${user}',false,null);`);
for(const file of ['202609200047_public_resources.sql','202609210060_resource_previews.sql','202609210060_resource_previews.sql']) await db.exec(fs.readFileSync('outputs/huideng_counter/supabase/migrations/'+file,'utf8').replace(/^\uFEFF/,''));
await db.query(`insert into public.public_resources(id,user_id,upload_id,file_name,file_size,checksum,mime_type,object_key,status,verified) values($1,$2,$1,'image.png',100,$3,'image/png','resources/image.png','published',true)`,[id,user,'a'.repeat(64)]);
const preview=async()=> (await db.query('select public.public_resource_preview($1,$2) r',[user,id])).rows[0].r;
assert.equal((await preview()).file.id,id);
await db.exec(`set role authenticated`);await assert.rejects(preview,/permission denied/);await db.exec('reset role');
await db.exec('update public.public_resource_settings set download_enabled=false where id');await assert.rejects(preview,/DOWNLOAD_DISABLED/);
await db.exec('update public.public_resource_settings set download_enabled=true where id');
await db.exec(`update public.public_resources set verified=false where id='${id}'`);await assert.rejects(preview,/FILE_UNAVAILABLE/);
await db.exec(`update public.public_resources set verified=true,status='deleted' where id='${id}'`);await assert.rejects(preview,/FILE_UNAVAILABLE/);
console.log('Preview authorization, disabled downloads, unpublished/unverified objects and direct-client denial passed');await db.close();
