import fs from 'node:fs';
import assert from 'node:assert/strict';
const {PGlite}=await import(process.env.PGLITE_MODULE??new URL('../../.dart_tool/group_resource_sql/node_modules/@electric-sql/pglite/dist/index.js',import.meta.url).href);
const db=new PGlite();
const admin='00000000-0000-4000-8000-000000000001',a='00000000-0000-4000-8000-000000000002',b='00000000-0000-4000-8000-000000000003';
await db.exec(`create role anon; create role authenticated; create role service_role;
 create schema auth; create schema admin_private;
 create table auth.users(id uuid primary key,banned_until timestamptz);
 create table admin_private.members(user_id uuid,enabled boolean,role text);
 create table public.app_user_levels(user_id uuid primary key,level integer);
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 insert into auth.users(id) values('${admin}'),('${a}'),('${b}');
 insert into admin_private.members values('${admin}',true,'super_admin');
 insert into public.app_user_levels values('${a}',5),('${b}',5);`);
const migration=fs.readFileSync(new URL('../drafts/202609290081_total_storage_quota.sql',import.meta.url),'utf8');
await db.exec(migration);await db.exec(migration);
const rpc=async(action,data={},actor=admin)=>(await db.query('select public.admin_storage_quota($1,$2,$3) v',[actor,action,data])).rows[0].v;
const get=u=>rpc('get',{user_id:u});
const put=(u,source,entity,bytes,kind='permanent')=>db.query('select quota_private.put_source($1,$2,$3,$4,$5)',[u,source,entity,bytes,kind]);
const remove=(u,source)=>db.query('select quota_private.remove_source($1,$2)',[u,source]);
const mb=1048576;
assert.deepEqual((await rpc('levels')).items.map(l=>l.bytes),[null,10240*mb,5120*mb,2048*mb,500*mb]);
assert.equal((await rpc('levels')).items[0].unlimited_storage,true);
assert.equal((await get(admin)).level,2);
assert.equal((await get(admin)).quota_bytes,10240*mb);
await assert.rejects(()=>rpc('level_save',{level:1,bytes:100,revision:0,request_id:crypto.randomUUID()}),/LEVEL_ONE_UNLIMITED/);
// A custom level template keeps the threshold scenarios small and readable.
await db.exec('update quota_private.levels set bytes=104857600 where level=5');
await assert.rejects(()=>rpc('levels',{},a),/FORBIDDEN/);
await put(a,'public/1','object/1',80*mb);
assert.equal((await get(a)).warning,'warning');
// Same user's references deduplicate; a different user's reference is charged.
await put(a,'group/1','object/1',80*mb);
await put(b,'group/2','object/1',80*mb);
assert.equal((await get(a)).used_bytes,80*mb);
assert.equal((await get(b)).used_bytes,80*mb);
await remove(a,'public/1');
assert.equal((await get(a)).used_bytes,80*mb);
await put(a,'upload/2','object/2',10*mb,'reserved');
assert.equal((await get(a)).warning,'critical');
assert.equal((await get(a)).reserved_bytes,10*mb);
// Reservation conversion with the same charge key cannot double-count bytes.
await put(a,'public/2','object/2',10*mb);
assert.equal((await get(a)).occupied_bytes,90*mb);
await remove(a,'upload/2');
await put(a,'temp/3','temporary/3',10*mb,'temporary');
assert.equal((await get(a)).warning,'full');
await assert.rejects(()=>put(a,'overflow','object/overflow',1),/STORAGE_QUOTA_EXCEEDED/);
assert.equal((await get(a)).occupied_bytes,100*mb);
await put(a,'group/another','object/1',80*mb);
assert.equal((await get(a)).occupied_bytes,100*mb);
const payload={user_id:a,revision:0,bytes:50*mb,request_id:crypto.randomUUID()};
let state=await rpc('override',payload);
assert.equal(state.over_bytes,50*mb);
assert.equal(state.used_bytes,100*mb);
assert.deepEqual(await rpc('override',payload),state);
await assert.rejects(()=>rpc('override',{...payload,bytes:60*mb}),/CONFIG_CONFLICT/);
await assert.rejects(()=>put(a,'new','new',1),/STORAGE_QUOTA_EXCEEDED/);
await put(a,'public/2','object/2',5*mb);
assert.equal((await get(a)).used_bytes,95*mb);
await remove(a,'group/1');await remove(a,'group/another');
assert.equal((await get(a)).used_bytes,15*mb);
assert.equal((await get(b)).used_bytes,80*mb);
state=await rpc('reset',{user_id:a,revision:1,request_id:crypto.randomUUID()});
assert.equal(state.quota_bytes,100*mb);assert.equal(state.override_bytes,null);
await rpc('level_save',{level:5,bytes:20*mb,revision:0,request_id:crypto.randomUUID()});
assert.equal((await get(a)).quota_bytes,20*mb);
assert.equal((await get(b)).over_bytes,60*mb);
// A level change never deletes sources and never changes feature permissions.
await db.exec(`update public.app_user_levels set level=1 where user_id='${b}'`);
assert.equal((await get(b)).quota_bytes,null);
assert.equal((await get(b)).unlimited_storage,true);
assert.equal((await get(b)).remaining_bytes,null);
assert.equal((await get(b)).usage_percent,null);
assert.equal((await get(b)).used_bytes,80*mb);
await rpc('override',{user_id:b,bytes:200*mb,revision:0,request_id:crypto.randomUUID()});
assert.equal((await get(b)).unlimited_storage,true);
await put(b,'large','large',20*1024*mb);
assert.equal((await get(b)).warning,'normal');
await remove(b,'large');
await db.exec(`update public.app_user_levels set level=5 where user_id='${b}'`);
assert.equal((await get(b)).quota_bytes,200*mb);
await db.exec('set role authenticated');
await assert.rejects(()=>put(a,'bypass','bypass',1),/permission denied/);
await assert.rejects(()=>rpc('levels'),/permission denied/);
await assert.rejects(()=>db.query('delete from quota_private.sources'),/permission denied/);
await db.exec('reset role');
await db.close();
console.log('Quota kernel passed: five levels, overrides, reset, per-user dedup, reservations, thresholds, downgrade, no data deletion, authorization and idempotency.');
