-- One-time renumbering; account UUIDs, friends, messages and QR tokens are untouched.
-- Start at 1000, continue through 9999 to 10000 and beyond. No number recycling.
begin;
lock table public.chat_profiles in access exclusive mode;
create table if not exists public.chat_number_migration_036 (
 user_id uuid primary key,
 old_number bigint not null unique,
 new_number bigint not null unique,
 migrated_at timestamptz not null default now()
);
alter table public.chat_number_migration_036 enable row level security;
revoke all on public.chat_number_migration_036 from public, anon, authenticated;

do $$
declare seq_name text; next_number bigint;
begin
 if not exists (select 1 from pg_constraint
   where conrelid='public.chat_profiles'::regclass and conname='chat_number_minimum_036') then
  insert into public.chat_number_migration_036(user_id,old_number,new_number)
    select user_id,personal_number,999+row_number() over(order by personal_number,user_id)
    from public.chat_profiles;
  alter table public.chat_profiles disable trigger chat_number_immutable;
  alter table public.chat_profiles alter column personal_number set generated by default;
  -- Use a disjoint temporary range to avoid unique-index collisions on updates.
  update public.chat_profiles p set personal_number=-m.new_number
    from public.chat_number_migration_036 m where p.user_id=m.user_id;
  update public.chat_profiles p set personal_number=m.new_number
    from public.chat_number_migration_036 m where p.user_id=m.user_id;
  alter table public.chat_profiles alter column personal_number set generated always;
  alter table public.chat_profiles enable trigger chat_number_immutable;
  alter table public.chat_profiles add constraint chat_number_minimum_036 check(personal_number>=1000);
  select coalesce(max(personal_number)+1,1000) into next_number from public.chat_profiles;
  seq_name:=pg_get_serial_sequence('public.chat_profiles','personal_number');
  -- Restart is transactional and invalidates cached sequence allocations.
  execute format('alter sequence %s restart with %s',seq_name,next_number);
 end if;
end $$;
commit;
